Dokapi_url: http://localhost:9130
okapi_url: ${Dokapi_url}
spring:
  application:
    name: edge-caiasoft
  jackson:
    default-property-inclusion: non_null
  liquibase:
    enabled: false
  flyway:
    enabled: false
management:
  endpoints:
    web:
      base-path: /admin
feign:
  client:
    config:
      default:
        loggerLevel: full

logging:
  level:
    org:
      springframework:
        cache: OFF

server.port: 8081
folio.tenant.validation.enabled: false
