openapi: 3.0.0
info:
  title: Edge CasiaSoft API
  version: v1
servers:
  - url: /asrService/asr/
paths:
  /lookupNewAsrItems:
    get:
      responses:
        '200':
          description: Success response
          content:
            text/plain:
              schema:
                type: string
